
language: node_js
node_js:
  - 'stable'
install: npm install
services:
    - mongodb
script: npm test

deploy:
    provider: lambda
    function_name: "resthub"
    region: "ap-southeast-1"
    role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
    runtime: "nodejs4.3"
    handler_name: "handler"

